#!/usr/bin/env bash

TEST=$1
RESP=$2
PORT=${3:-9090}

. ../resty -W 127.0.0.1:$PORT

# run tests to check that the correct request is being made
( j=1
  while true; do
    gnetcat -l -w 1 -p $PORT \
      -e 'while read -t 1 a; do echo "$a"; done' localhost || break
    grep '^# TEST [0-9][0-9]*' $TEST |head -$j |tail -1 && j=$((j+1))
  done )&

. $TEST

wait

# run tests again, this time checking actual output
( j=1
  while true; do
    gnetcat -l -w 1 -p $PORT -e "cat $RESP" localhost || break
    grep '^# TEST [0-9][0-9]*' $TEST |head -$j |tail -1 && j=$((j+1))
  done )&

. $TEST

wait
